-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ==========================================
-- 1. Helper Functions (Prevent Recursion)
-- ==========================================

-- Function to check membership safely (bypasses RLS)
create or replace function public.is_ledger_member(_ledger_id uuid)
returns boolean as $$
begin
  return exists (
    select 1
    from public.ledger_members
    where ledger_id = _ledger_id
    and user_id = auth.uid()
  );
end;
$$ language plpgsql security definer;

-- Function to check role safely (bypasses RLS)
create or replace function public.get_my_role(_ledger_id uuid)
returns text as $$
declare
  _role text;
begin
  select role into _role
  from public.ledger_members
  where ledger_id = _ledger_id
  and user_id = auth.uid();
  return _role;
end;
$$ language plpgsql security definer;

-- ==========================================
-- 2. Tables & Schema
-- ==========================================

-- Profiles
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.profiles enable row level security;

-- Ledgers
create table if not exists public.ledgers (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users not null
);
alter table public.ledgers enable row level security;

-- Ledger Members
create table if not exists public.ledger_members (
  id uuid default uuid_generate_v4() primary key,
  ledger_id uuid references public.ledgers on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  role text default 'member' check (role in ('owner', 'admin', 'member')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(ledger_id, user_id)
);
alter table public.ledger_members enable row level security;

-- Transactions (Ensure ledger_id exists)
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  amount numeric not null,
  type text not null check (type in ('income', 'expense')),
  category text not null,
  date date not null default current_date,
  note text,
  user_id uuid references auth.users not null
);
alter table public.transactions enable row level security;

-- Add ledger_id column if it doesn't exist (idempotent)
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'transactions' and column_name = 'ledger_id') then
        alter table public.transactions add column ledger_id uuid references public.ledgers on delete cascade;
    end if;
end $$;

-- Categories (Customizable by ledger members)
create table if not exists public.categories (
  id uuid default uuid_generate_v4() primary key,
  ledger_id uuid references public.ledgers on delete cascade not null,
  user_id uuid references auth.users not null,
  type text not null check (type in ('income', 'expense')),
  name text not null,
  icon text not null,
  sort_order integer default 0,
  is_default boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(ledger_id, type, name)
);
alter table public.categories enable row level security;

-- ==========================================
-- 3. RLS Policies
-- ==========================================

-- Profiles
drop policy if exists "Public profiles are viewable by everyone" on public.profiles;
create policy "Public profiles are viewable by everyone" on public.profiles for select using ( true );

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile" on public.profiles for insert with check ( auth.uid() = id );

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update using ( auth.uid() = id );

-- Ledgers
drop policy if exists "Users can view ledgers they belong to" on public.ledgers;
create policy "Users can view ledgers they belong to" on public.ledgers for select
  using ( 
    public.is_ledger_member(id) 
    OR 
    created_by = auth.uid() -- Allow creator to see it immediately (crucial for rpc/inserts)
  );

drop policy if exists "Users can create ledgers" on public.ledgers;
create policy "Users can create ledgers" on public.ledgers for insert with check ( auth.uid() = created_by );

drop policy if exists "Users can update ledgers they admin" on public.ledgers;
create policy "Users can update ledgers they admin" on public.ledgers for update
  using ( public.get_my_role(id) in ('owner', 'admin') );

-- Ledger Members
drop policy if exists "Members can view other members" on public.ledger_members;
create policy "Members can view other members" on public.ledger_members for select
  using (
    user_id = auth.uid() 
    OR
    public.is_ledger_member(ledger_id)
  );

drop policy if exists "Owners can add members" on public.ledger_members;
create policy "Owners can add members" on public.ledger_members for insert
  with check (
    public.get_my_role(ledger_id) in ('owner', 'admin')
    OR
    -- Allow initial owner insertion
    (
      not exists (select 1 from public.ledger_members where ledger_id = public.ledger_members.ledger_id)
      and
      exists (select 1 from public.ledgers where id = public.ledger_members.ledger_id and created_by = auth.uid())
    )
  );

drop policy if exists "Owners can remove members" on public.ledger_members;
create policy "Owners can remove members" on public.ledger_members for delete
  using (
    -- Must be owner or admin of the ledger
    public.get_my_role(ledger_id) in ('owner', 'admin')
    AND
    -- Cannot remove yourself
    user_id != auth.uid()
  );

-- Transactions
drop policy if exists "Users can view their own transactions" on public.transactions;
drop policy if exists "Users can insert their own transactions" on public.transactions;
drop policy if exists "Users can update their own transactions" on public.transactions;
drop policy if exists "Users can delete their own transactions" on public.transactions;

drop policy if exists "Users can view transactions from their ledgers" on public.transactions;
create policy "Users can view transactions from their ledgers" on public.transactions for select
  using ( public.is_ledger_member(ledger_id) );

drop policy if exists "Users can insert transactions into their ledgers" on public.transactions;
create policy "Users can insert transactions into their ledgers" on public.transactions for insert
  with check ( public.is_ledger_member(ledger_id) );

drop policy if exists "Users can update transactions in their ledgers" on public.transactions;
create policy "Users can update transactions in their ledgers" on public.transactions for update
  using ( public.is_ledger_member(ledger_id) );

drop policy if exists "Users can delete transactions in their ledgers" on public.transactions;
create policy "Users can delete transactions in their ledgers" on public.transactions for delete
  using ( public.is_ledger_member(ledger_id) );

-- Categories
drop policy if exists "Ledger members can view categories" on public.categories;
create policy "Ledger members can view categories" on public.categories for select
  using ( public.is_ledger_member(ledger_id) );

drop policy if exists "Ledger members can insert categories" on public.categories;
create policy "Ledger members can insert categories" on public.categories for insert
  with check ( public.is_ledger_member(ledger_id) );

drop policy if exists "Ledger members can update categories" on public.categories;
create policy "Ledger members can update categories" on public.categories for update
  using ( public.is_ledger_member(ledger_id) );

drop policy if exists "Ledger members can delete non-default categories" on public.categories;
create policy "Ledger members can delete non-default categories" on public.categories for delete
  using ( public.is_ledger_member(ledger_id) AND is_default = false );


-- ==========================================
-- 4. Triggers & RPCs
-- ==========================================

-- Profile Creation Trigger (Enhanced with default categories)
create or replace function public.handle_new_user()
returns trigger as $$
declare
  new_ledger_id uuid;
begin
  -- 1. Create Profile
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;

  -- 2. Create Default Ledger (only if none exists)
  if not exists (select 1 from public.ledgers where created_by = new.id) then
      insert into public.ledgers (name, created_by)
      values ('默认账本', new.id)
      returning id into new_ledger_id;

      -- 3. Add Member (Owner)
      insert into public.ledger_members (ledger_id, user_id, role)
      values (new_ledger_id, new.id, 'owner');

      -- 4. Insert Default Categories
      -- Default expense categories
      insert into public.categories (ledger_id, user_id, type, name, icon, sort_order, is_default) values
      (new_ledger_id, new.id, 'expense', '餐饮', 'Utensils', 10, true),
      (new_ledger_id, new.id, 'expense', '交通', 'Bus', 9, true),
      (new_ledger_id, new.id, 'expense', '购物', 'ShoppingBag', 8, true),
      (new_ledger_id, new.id, 'expense', '居住', 'Home', 7, true),
      (new_ledger_id, new.id, 'expense', '水电', 'Zap', 6, true),
      (new_ledger_id, new.id, 'expense', '娱乐', 'Gamepad2', 5, true),
      (new_ledger_id, new.id, 'expense', '教育', 'GraduationCap', 4, true),
      (new_ledger_id, new.id, 'expense', '医疗', 'Stethoscope', 3, true),
      (new_ledger_id, new.id, 'expense', '旅行', 'Plane', 2, true),
      (new_ledger_id, new.id, 'expense', '其他', 'MoreHorizontal', 1, true);
      -- Default income categories
      insert into public.categories (ledger_id, user_id, type, name, icon, sort_order, is_default) values
      (new_ledger_id, new.id, 'income', '工资', 'Wallet', 6, true),
      (new_ledger_id, new.id, 'income', '奖金', 'DollarSign', 5, true),
      (new_ledger_id, new.id, 'income', '理财', 'TrendingUp', 4, true),
      (new_ledger_id, new.id, 'income', '礼金', 'Gift', 3, true),
      (new_ledger_id, new.id, 'income', '固收', 'Briefcase', 2, true),
      (new_ledger_id, new.id, 'income', '其他收入', 'MoreHorizontal', 1, true);
  end if;

  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Atomic Ledger Creation RPC (with default categories)
-- Drop old signature if exists to allow cleaner rename
drop function if exists public.create_ledger(text);

create or replace function public.create_ledger(new_ledger_name text)
returns json as $$
declare
  new_ledger_id uuid;
  new_ledger_record record;
begin
  -- 1. Insert Ledger
  insert into public.ledgers (name, created_by)
  values (new_ledger_name, auth.uid())
  returning id, name, created_at, created_by into new_ledger_record;

  new_ledger_id := new_ledger_record.id;

  -- 2. Insert Member (Owner)
  insert into public.ledger_members (ledger_id, user_id, role)
  values (new_ledger_id, auth.uid(), 'owner');

  -- 3. Insert Default Categories
  -- Default expense categories
  insert into public.categories (ledger_id, user_id, type, name, icon, sort_order, is_default) values
  (new_ledger_id, auth.uid(), 'expense', '餐饮', 'Utensils', 10, true),
  (new_ledger_id, auth.uid(), 'expense', '交通', 'Bus', 9, true),
  (new_ledger_id, auth.uid(), 'expense', '购物', 'ShoppingBag', 8, true),
  (new_ledger_id, auth.uid(), 'expense', '居住', 'Home', 7, true),
  (new_ledger_id, auth.uid(), 'expense', '水电', 'Zap', 6, true),
  (new_ledger_id, auth.uid(), 'expense', '娱乐', 'Gamepad2', 5, true),
  (new_ledger_id, auth.uid(), 'expense', '教育', 'GraduationCap', 4, true),
  (new_ledger_id, auth.uid(), 'expense', '医疗', 'Stethoscope', 3, true),
  (new_ledger_id, auth.uid(), 'expense', '旅行', 'Plane', 2, true),
  (new_ledger_id, auth.uid(), 'expense', '其他', 'MoreHorizontal', 1, true);
  -- Default income categories
  insert into public.categories (ledger_id, user_id, type, name, icon, sort_order, is_default) values
  (new_ledger_id, auth.uid(), 'income', '工资', 'Wallet', 6, true),
  (new_ledger_id, auth.uid(), 'income', '奖金', 'DollarSign', 5, true),
  (new_ledger_id, auth.uid(), 'income', '理财', 'TrendingUp', 4, true),
  (new_ledger_id, auth.uid(), 'income', '礼金', 'Gift', 3, true),
  (new_ledger_id, auth.uid(), 'income', '固收', 'Briefcase', 2, true),
  (new_ledger_id, auth.uid(), 'income', '其他收入', 'MoreHorizontal', 1, true);

  return row_to_json(new_ledger_record);
end;
$$ language plpgsql security definer;

-- ==========================================
-- 5. Data Backfill (One-off)
-- ==========================================

-- Backfill profiles for existing users
insert into public.profiles (id, email)
select id, email from auth.users
on conflict (id) do nothing;

-- Backfill default categories for existing ledgers that have none
do $$
declare
  ledger_record record;
begin
  for ledger_record in
    select l.id, l.created_by
    from public.ledgers l
    where not exists (
      select 1 from public.categories c where c.ledger_id = l.id
    )
  loop
    -- Insert default expense categories
    insert into public.categories (ledger_id, user_id, type, name, icon, sort_order, is_default) values
    (ledger_record.id, ledger_record.created_by, 'expense', '餐饮', 'Utensils', 10, true),
    (ledger_record.id, ledger_record.created_by, 'expense', '交通', 'Bus', 9, true),
    (ledger_record.id, ledger_record.created_by, 'expense', '购物', 'ShoppingBag', 8, true),
    (ledger_record.id, ledger_record.created_by, 'expense', '居住', 'Home', 7, true),
    (ledger_record.id, ledger_record.created_by, 'expense', '水电', 'Zap', 6, true),
    (ledger_record.id, ledger_record.created_by, 'expense', '娱乐', 'Gamepad2', 5, true),
    (ledger_record.id, ledger_record.created_by, 'expense', '教育', 'GraduationCap', 4, true),
    (ledger_record.id, ledger_record.created_by, 'expense', '医疗', 'Stethoscope', 3, true),
    (ledger_record.id, ledger_record.created_by, 'expense', '旅行', 'Plane', 2, true),
    (ledger_record.id, ledger_record.created_by, 'expense', '其他', 'MoreHorizontal', 1, true);
    -- Insert default income categories
    insert into public.categories (ledger_id, user_id, type, name, icon, sort_order, is_default) values
    (ledger_record.id, ledger_record.created_by, 'income', '工资', 'Wallet', 6, true),
    (ledger_record.id, ledger_record.created_by, 'income', '奖金', 'DollarSign', 5, true),
    (ledger_record.id, ledger_record.created_by, 'income', '理财', 'TrendingUp', 4, true),
    (ledger_record.id, ledger_record.created_by, 'income', '礼金', 'Gift', 3, true),
    (ledger_record.id, ledger_record.created_by, 'income', '固收', 'Briefcase', 2, true),
    (ledger_record.id, ledger_record.created_by, 'income', '其他收入', 'MoreHorizontal', 1, true);
  end loop;
end;
$$;

-- ==========================================
-- 6. Gold Investments (黄金理财)
-- ==========================================

-- Gold Investments table
create table if not exists public.gold_investments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  ledger_id uuid references public.ledgers on delete cascade not null,
  grams numeric not null,
  total_price numeric not null,
  price_per_gram numeric not null,
  date date not null default current_date,
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.gold_investments enable row level security;

-- RLS Policies for gold_investments
drop policy if exists "Users can view gold investments from their ledgers" on public.gold_investments;
create policy "Users can view gold investments from their ledgers" on public.gold_investments for select
  using ( public.is_ledger_member(ledger_id) );

drop policy if exists "Users can insert gold investments into their ledgers" on public.gold_investments;
create policy "Users can insert gold investments into their ledgers" on public.gold_investments for insert
  with check ( public.is_ledger_member(ledger_id) );

drop policy if exists "Users can update gold investments in their ledgers" on public.gold_investments;
create policy "Users can update gold investments in their ledgers" on public.gold_investments for update
  using ( public.is_ledger_member(ledger_id) );

drop policy if exists "Users can delete gold investments in their ledgers" on public.gold_investments;
create policy "Users can delete gold investments in their ledgers" on public.gold_investments for delete
  using ( public.is_ledger_member(ledger_id) );
