-- Create transactions table
create table public.transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  amount numeric not null,
  type text not null check (type in ('income', 'expense')),
  category text not null,
  date date not null default current_date,
  note text,
  user_id uuid references auth.users not null
);

-- Enable RLS
alter table public.transactions enable row level security;

-- Create policy to allow users to see only their own transactions
create policy "Users can view their own transactions"
on public.transactions for select
using (auth.uid() = user_id);

create policy "Users can insert their own transactions"
on public.transactions for insert
with check (auth.uid() = user_id);

create policy "Users can update their own transactions"
on public.transactions for update
using (auth.uid() = user_id);

create policy "Users can delete their own transactions"
on public.transactions for delete
using (auth.uid() = user_id);
